import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { join } from "node:path";
import { mkdirSync, rmSync, existsSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { writeEffectivePrompt } from "../src/agent/prompts/effective-prompt.js";

const TEST_DIR = join(tmpdir(), "ao-effective-prompt-test");

beforeEach(() => {
  mkdirSync(TEST_DIR, { recursive: true });
});

afterEach(() => {
  if (existsSync(TEST_DIR)) rmSync(TEST_DIR, { recursive: true });
});

describe("writeEffectivePrompt", () => {
  it("writes snapshot file with header and content", () => {
    const agentDir = join(TEST_DIR, "agents", "bot");
    writeEffectivePrompt(
      agentDir,
      { text: "Hello prompt", hash: "abc123def456" },
      { mode: "full", version: "v1" },
    );

    const dest = join(agentDir, ".effective-prompt.md");
    expect(existsSync(dest)).toBe(true);
    const content = readFileSync(dest, "utf-8");
    expect(content).toContain("<!-- Generated by agent-office");
    expect(content).toContain("Mode: full");
    expect(content).toContain("Version: v1");
    expect(content).toContain("Hash: abc123def456");
    expect(content).toContain("Hello prompt");
  });

  it("creates parent directory if missing", () => {
    const agentDir = join(TEST_DIR, "deep", "nested", "agent");
    writeEffectivePrompt(
      agentDir,
      { text: "Prompt text", hash: "aaa111bbb222" },
      { mode: "minimal", version: "v1" },
    );
    expect(existsSync(join(agentDir, ".effective-prompt.md"))).toBe(true);
  });

  it("overwrites existing snapshot on regeneration", () => {
    const agentDir = join(TEST_DIR, "agents", "bot");
    writeEffectivePrompt(
      agentDir,
      { text: "First prompt", hash: "hash1hash1ha" },
      { mode: "full", version: "v1" },
    );
    writeEffectivePrompt(
      agentDir,
      { text: "Second prompt", hash: "hash2hash2ha" },
      { mode: "full", version: "v1" },
    );
    const content = readFileSync(
      join(agentDir, ".effective-prompt.md"),
      "utf-8",
    );
    expect(content).toContain("Second prompt");
    expect(content).not.toContain("First prompt");
  });

  it("does not throw on write failure", () => {
    // Pass a path that can't be created (null byte)
    expect(() =>
      writeEffectivePrompt(
        "/dev/null/\0invalid",
        { text: "text", hash: "abcdef123456" },
        { mode: "full", version: "v1" },
      ),
    ).not.toThrow();
  });
});
