import type { CSSVariablesResolver } from "@mantine/core";

export const cssVariablesResolver: CSSVariablesResolver = () => ({
  variables: {
    "--ao-radius-squircle": "22%",
    "--ao-font-mono":
      '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
  },
  light: {
    "--ao-bg-body": "#faf8f5",
    "--ao-bg-surface": "#ffffff",
    "--ao-bg-surface-hover": "#f5f0eb",
    "--ao-bg-sidebar": "#f5f0eb",
    "--ao-bg-sidebar-hover": "#ebe5dd",
    "--ao-bg-sidebar-active": "#d5e4d8",
    "--ao-bg-input": "#ffffff",
    "--ao-bg-elevated": "#faf8f5",
    "--ao-bg-code": "#f0ebe4",
    "--ao-bg-code-block": "#f5f0eb",
    "--ao-text-primary": "#1c1917",
    "--ao-text-secondary": "#57534e",
    "--ao-text-muted": "#a8a29e",
    "--ao-text-bright": "#0c0a09",
    "--ao-text-sidebar": "#57534e",
    "--ao-text-sidebar-bright": "#1c1917",
    "--ao-border": "#d6d3d1",
    "--ao-border-input": "#a8a29e",
    "--ao-border-input-focus": "#4f8058",
    "--ao-accent-blue": "#1c7ed6",
    "--ao-accent-green": "#2f9e44",
    "--ao-accent-red": "#e03131",
    "--ao-accent-yellow": "#e67700",
    "--ao-accent-sage": "#4f8058",
    "--ao-online-green": "#2f9e44",
    "--ao-mention-badge": "#e03131",
  },
  dark: {
    "--ao-bg-body": "#1c1917",
    "--ao-bg-surface": "#292524",
    "--ao-bg-surface-hover": "#352f2b",
    "--ao-bg-sidebar": "#1c1917",
    "--ao-bg-sidebar-hover": "#352f2b",
    "--ao-bg-sidebar-active": "#27432e",
    "--ao-bg-input": "#292524",
    "--ao-bg-elevated": "#1c1917",
    "--ao-bg-code": "#231f1d",
    "--ao-bg-code-block": "#1a1614",
    "--ao-text-primary": "#e7e5e4",
    "--ao-text-secondary": "#a8a29e",
    "--ao-text-muted": "#78716c",
    "--ao-text-bright": "#ffffff",
    "--ao-text-sidebar": "#d6d3d1",
    "--ao-text-sidebar-bright": "#ffffff",
    "--ao-border": "#44403c",
    "--ao-border-input": "#57534e",
    "--ao-border-input-focus": "#5f9268",
    "--ao-accent-blue": "#74c0fc",
    "--ao-accent-green": "#51cf66",
    "--ao-accent-red": "#ff6b6b",
    "--ao-accent-yellow": "#fcc419",
    "--ao-accent-sage": "#b5cfba",
    "--ao-online-green": "#51cf66",
    "--ao-mention-badge": "#ff6b6b",
  },
});
